### ISSUE TITLE
[Feature] Settings Menu TimeUntilClose MaxMenuWidth

### ISSUE THREAD

**Issue by jakkaas** [Hofknecht/SystemTrayMenu#154]
Would like to have an option of SystemTrayMenu following the mouse arrow key. Also in setting give us an option of selecting the time after which the menu disappears.

**Comment by Hofknecht** [comment]
relate first point "following the mouse arrow key" 
sound like [Feature] Option to appear at mouse location #135
do you mean to appear at mouse location?
we tought about it and came to the decision to not implement it because you normally would either use the mouse and click on it or use the keyboard not both at same time
i will reopen and link this, that we have a task foreach topic

related second point "time after which the menu disappears
in code it is at the moment in MenuDefines.cs
`internal const int TimeUntilClose = 1000;`
i agree we can put into settings menu
(Maybe addionally i will put MaxMenuWidth = 300 also into settings menu)
i will rename this task to "Settings Menu TimeUntilClose MaxMenuWidth"

**Comment by Hofknecht** [comment]
@jakkaas 
thank you, this task '[Feature] Settings Menu TimeUntilClose MaxMenuWidth #154'
is now in master (only translations missing for other than english, coming soon with [Feature] Add Languages #156)

![image](https://user-images.githubusercontent.com/52528841/116005790-ca5d6680-a608-11eb-8b2e-334d1f51aec7.png)
also your related issue #135 putted as control in settings gui, but not yet implemented and aktivated, therfore follow #135

please try the parameters #154 in master or next release or see screenshot and give us feedback if it is what you expected and if you have further questions / ideas

**Comment by Hofknecht** [comment]
changed default value for time to open to 100
