### ISSUE TITLE
[Feature] Update Microsoft Store app to lastest version

### ISSUE THREAD

**Issue by the-phuctran** [Hofknecht/SystemTrayMenu#197]
I would like to use uwp version but it seems no longer updated

**Comment by Hofknecht** [comment]
Thank you for the hint to update microsoft store version 
(how we do this is described in #117)

submitted latest version to store, takes normally 1-3 days

status:
https://partner.microsoft.com/de-de/dashboard/products/9N24F8ZBJMT1/submissions/1152921505693945876/CertificationStatus

(but e.g. #131 still a problem with uwp, it could be that #195 has the same problem because we are using also registry keys there.)

let's see

**Comment by Hofknecht** [comment]
i just see some warnings/errors in the final report
![2021-09-24 20_45_16-Window](https://user-images.githubusercontent.com/52528841/134725075-f682329f-311e-4cb3-b0d9-e9d89724ddc9.png)


[ValidationResult.zip](https://github.com/Hofknecht/SystemTrayMenu/files/7227838/ValidationResult.zip)

**Comment by Hofknecht** [comment]
<html>
<body>


Übermittlung: 9 | Im Microsoft Store | 24.09.2021
-- | -- | --



</body>
</html>

done

**Comment by Hofknecht** [comment]
(in uwp app main issue is autostart not working #131)

@the-phuctran
looking forward to hear if it is working fine for you
