### ISSUE TITLE
[Feature] Share app to chocolatey.org

### ISSUE THREAD

**Issue by picu63** [Hofknecht/SystemTrayMenu#208]
Hi,
I'll be nice if SystemTrayMenu will be on chocolatey.org or other similar package provider.
Specially when taskbar in Windows 11 is highly limited.
Thanks

**Comment by Tanjalibertatis** [comment]
I followed this instruction: 
https://weblog.west-wind.com/posts/2017/jan/29/creating-a-portable-and-embedded-chocolatey-package#embedded-binary-packages

finished until step "choco pack" - choco install has not worked yet

(and found a few example projects here: 
https://stackoverflow.com/questions/45255168/can-i-create-a-chocolatey-package-for-an-exe-that-isnt-an-installer)

**Comment by Tanjalibertatis** [comment]
![2021-11-28 21_44_10-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/62262740/143785459-88b61c74-989b-4928-88e7-6300c96e899d.png)

check status here: 
https://community.chocolatey.org/packages/systemtraymenu/1.1.1.0

**Comment by Tanjalibertatis** [comment]
-files for package are located at C:\Windows\System32\SystemTrayMenu

![2021-12-12 13_02_50-Window](https://user-images.githubusercontent.com/62262740/145711391-d31f5f59-2453-470b-8258-c72e70fea724.png)
=> VERIFICATION.txt file missing when binaries included (package)

So I added a file named VERIFICATION.txt (located at C:\Windows\System32\test\tools\VERIFICATION.txt) with 
`choco new test`
edited and put it into C:\Windows\System32\SystemTrayMenu\tools

After that I updated everything to new version 1.2.0.0 and pushed to chocolatey.

Check status here: https://community.chocolatey.org/packages/systemtraymenu/1.2.0.0

**Comment by phanirithvij** [comment]
It is available via [Scoop](https://scoop.sh)

**Comment by Tanjalibertatis** [comment]
package was reviewed, but there are some changes to make:

1) The iconUrl should be switched from github raw to a CDN: https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines
=> done by using https://statically.io/
2) The checksums need to be filled in.
3) Are you the author of this software? If you are, please confirm with a comment here. If you are not, can you please put your Chocolatey username in the owners field in the nuspec and the software author's name in the authors field.
=> done by commenting discussion with "Yes, I am the author of this software."
4) The packageSourceUrl is for the source for the Chocolatey package (e.g. the .nuspec, chocolateyinstall.ps1, etc), not for where the source for the software that the package installs is.
5) Since the 32 bit and 64 bit urls are the same, the 64 bit url and checksum can be removed. Chocolatey will go ahead and use the 32 bit url on 64 bit systems
=> I don't know where to remove these.
6) Please fill in the VERIFICATION.txt with explicit steps on how to verify the included binaries are the same as the binaries published by the project. Example: https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/7zip.install/legal/VERIFICATION.txt
=> I don't know what to change here, because I followed the instructions 'Software Author / Vendor Specific' here: https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0006. For me that means that if you are the software author, checksums or something else are optional.
7) Please fill in the LICENSE.txt instead of just using a license identifier.
=> done by copying the whole license text
8) Since the package is extracting a zip with Install-ChocolateyZipPackage into the $toolsDir, there should be no need for the uninstall script.
=> done by deleting the file chocolateyuninstall.ps1

=> points 1, 3, 7 and 8 are done,
2, 4, 5, 6 must be completed before pushing again (Attention: 'repush your updated package with the exact same version')

**Comment by Tanjalibertatis** [comment]
The reviewer answered:

> So looking back at this package, it seems like the included files in the .nupkg are the same as the files in the archive that is downloaded and extracted with the install script. Is that correct?
> 
> So I actually think you don't need the install script at all, if that is the case.

So I deleted chocolateyinstall.ps1 and repushed the package

**Comment by Tanjalibertatis** [comment]
> Status Change - Changed status of package from 'submitted' to 'approved'.

Test also worked well. 

Just pushed latest version 1.2.3.

**Comment by Tanjalibertatis** [comment]
> FYI: It is available via [Scoop](https://scoop.sh)

@phanirithvij that's nice, thank you!
So far we were not able to install SystemTrayMenu via scoop. 
We found the [GitHub bucket](https://github.com/KnotUntied/scoop-knotuntied/blob/master/bucket/systemtraymenu.json), thanks for that, we gave the project a star!

But when we type the commands
`scoop install systemtraymenu` or  `scoop install SystemTrayMenu`
the following error message appears: `Couldn't find manifest for 'systemtraymenu'.`


Could you maybe help us?

**Comment by Tanjalibertatis** [comment]
Thank you @phanirithvij we got it now!
We have documented it here (#325) and will add it to the readme.

**Comment by phanirithvij** [comment]
@Tanjalibertatis I'm really sorry I missed this in my inbox. Thanks for adding it to the readme.
