### ISSUE TITLE
[BUG] Right click on items to choose "Send to" doesn't work

### ISSUE THREAD

**Issue by the-phuctran** [Hofknecht/SystemTrayMenu#225]
**Description, Steps to reproduce, Expected behavior, Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/43033446/138806498-5c3a35b7-509b-402e-9a57-79b568bf193b.png)
This option doesn't work in the right-click menu

 - OS: Windows 11 Pro, 21H2, 22000.282
 - Version 1.0.24.0, Microsoft store.

**Comment by Hofknecht** [comment]
related to ShellContextMenu there is also this minor issue, the context menu of a network root folder does not work
![900 context menu network root folder not working](https://user-images.githubusercontent.com/52528841/145644835-25df560a-6c20-4117-9f80-635d4ea74f2b.png)

when we change to another solution maybe also check this issue or create then an extra one therefore

**Comment by Hofknecht** [comment]
a third point is that dark mode not working in this ShellContextMenu:
![2021-12-11 11_15_29-Window](https://user-images.githubusercontent.com/52528841/145672965-265fcea2-5d5b-4fde-a267-201440efb9ff.png)

should look like this:
![2021-12-11 11_15_10-](https://user-images.githubusercontent.com/52528841/145672987-d49e1e72-a98a-42e2-bb83-f00d3005e5d2.png)

**Comment by chip33** [comment]
Right click on items to choose "Send to" doesn't work #225 can be fixed by modifying ShellContextMenu.cs as described [here](https://www.codeproject.com/Articles/22012/Explorer-Shell-Context-Menu?msg=3706303#xx3706303xx) 

Method ShellContextMenu.ShowContextMenu first calls User32.dll DestroyMenu then calls IContextMenu.InvokeCommand, using the menu id of the previous destroyed menu.

ShellContextMenu.InvokeContextMenuDefault does it in the right order.

Changed the order of calls, then it worked.


```
private void ShowContextMenu(Point pointScreen)
{
    ...

        uint nSelected = TrackPopupMenuEx(
            pMenu,
            TPM.RETURNCMD,
            pointScreen.X,
            pointScreen.Y,
            this.Handle,
            IntPtr.Zero);

        // First invoke menu item, then destroy menu.
        if (nSelected != 0)
        {
            InvokeCommand(_oContextMenu, nSelected, _strParentFolder, pointScreen);
        }

        DestroyMenu(pMenu);
        pMenu = IntPtr.Zero;

    ...
}
```

I have compiled latest commit 1.2.2.4 with this change to ShellContextMenu.cs and Send to now works for me.
[ShellContextMenu.zip](https://github.com/Hofknecht/SystemTrayMenu/files/7920184/ShellContextMenu.zip)

**Comment by Hofknecht** [comment]
@chip33 Thank you for analyzing finding the solution!
Seems to work great, comitted it with version 1.2.2.5!

@the-phuctran 
 FYI Thank you for reporting!

the other 2 related issues are now in #298

=> closed

**Comment by chip33** [comment]
Hi, you are welcome, glad to help with such a great project :)
