### ISSUE TITLE
[Feature] Classic theme support

### ISSUE THREAD

**Issue by Clasurol** [Hofknecht/SystemTrayMenu#250]
Program is great but I'd love to see it support the original classic theme in Windows. Cheers.

**Comment by Hofknecht** [comment]
i found a screenshot from windows 10 classic theme
![preview-1-9233](https://user-images.githubusercontent.com/52528841/143470021-b69f424a-f6c2-4748-90f5-a3b6b250451b.png)

at the moment we can only configure some colors here
![2021-11-25 16_43_27-Window](https://user-images.githubusercontent.com/52528841/143470372-2b3d5a06-2e9d-4037-8b0f-a24d805c52d9.png)

maybe you like to pick out the colors so that it gets the impression of a classic theme?

maybe you have some suggestions which controls needs addional changes and we can create here a todo list for it

**Comment by Hofknecht** [comment]
Currently we are not planning to change it so we will close this issue for now, maybe something for the future.

if someone wants to advance the topic, they can set the colors in the STM and post the color codes and a screenshot here, then we can discuss it further
