### ISSUE TITLE
[Feature] Multiple instances

### ISSUE THREAD

**Issue by GitBinet** [Hofknecht/SystemTrayMenu#252]
it will be interesting to have the possibility of being able to have several instances simultaneously with SystemTrayMenu with different root folder

**Comment by Hofknecht** [comment]
@GitBinet 
Thank you for the feedback!

i just checked it and that was actually a discussion between @topeterk and @verdammt89x in July 2019

resulted in the realization that you actually achieve the same thing if you put shortcuts from folders into the main folder

i know it it now the exact same e.g. with mouse you have to first go to STM main menu, then to subfolder.
But by keyboard you press the hotkey and then typy in your needed folder, then press enter.

I assume e.g. hotkey will be a big topic for several instances.

at the moment at startup there is our class SingleAppInstance.cs which contains a check IsAnyOtherInstancesofAppAlreadyRunning(), when true then we execute KillOtherInstancesOfApp()
i like this behavior very much, because it solves a lot of issues.

**Comment by Hofknecht** [comment]
currently we are not planning to change it so we will close this issue for now, maybe something for the future
