### ISSUE TITLE
[Feature] Open menu preferably to the right

### ISSUE THREAD

**Issue by terencemcdonnell** [Hofknecht/SystemTrayMenu#262]
Hello;

Love the app - have written something similar, but yours is superior so I am abandoning development.

One enhancement (at least to me) would be to have submenus fly-out to the right rather than left (assuming you do not have menu configured to bottom right corner).  I understand that this is dictated by window location, but if I have menu open in the middle of my screen, it would be nice to have default flow go left-to-right (or have option to specify this).  I believe this is the way that MS originally had this implemented.

Anyway, thank you!

**Comment by Hofknecht** [comment]
thanks for the feedback!

yes, we noticed that a short time ago, we see it that way too, it should open to the right by default, unless it is on the right edge

**Comment by Hofknecht** [comment]
@terencemcdonnell 
is now fixed

we are happy about all hints, plz give us more 

maybe you had more ideas in your app that we can use again here we are open to anything. Would be cool if we could get you as a contributor. Maybe you have your own ideas, otherwise we would also have a few on our internal roadmap ; )

**Comment by Hofknecht** [comment]
ah ok now i saw it right after releasing it doesn't work if the setting is that it should appear at the bottom left. I have now fixed that with version 1.2.0.1
