### ISSUE TITLE
[Feature] Reset 'Custom location' after display changed event e.g. rdp and custom location not more within screen bounds

### ISSUE THREAD

**Issue by petersnows25** [Hofknecht/SystemTrayMenu#269]
**Description, Steps to reproduce, Expected behavior, Screenshots**
Windows 11
Works on the computer itself.

Access the Computer using RDP
Does not show the menu.

**Comment by Hofknecht** [comment]
Normally, all variations of RDP should work. For example, we test this on several devices with different OS and different resolutions and different DPI settings and access win 10 computers. It always works there.

At the moment I don't have windows 11 to test, but of course it should behave in exactly the same way.

Can you open the settings menu via rdp and then set it there so that it appears at the bottom right or at the bottom left. Is there a difference? Does it really never show up? Maybe also play around with appear at mouse location and drag to location (therefore drag it to the correct location and press settings then 'ok' to save the custom location)

Normally the STM should restart when there is a display change, but maybe make a manual restart after connected via rdb.

Can you try out whether it works via the hotkey and then e.g. down arrow and enter, so it would theoretically start the first element in the STM. So does the menu just not appear on the screen?

 or does something crash when the menu appears? Maybe you can add your log file here or see if there are relevant lines in the log file.

I can also imagine that the systemtray click is not working so maybe try to use the option 'show in taskbar' as well.

Do other apps also have issues with screenbounds?

Let us know if something of that solves the issue.

We consider to upgrade one of our pc's to windows 11.

**Comment by petersnows25** [comment]
"Can you open the settings menu via rdp and then set it there so that it appears at the bottom right or at the bottom left. Is there a difference?"

Yes, that way works.
It was configured for "Custom" before.


"I can also imagine that the systemtray click is not working so maybe try to use the option 'show in taskbar' as well"
Systemtray Works
Right Click also works , enables me to see the menu (Settings/Log File/ Help/About/ Restart/ Exit).

"Do other apps also have issues with screenbounds?"
Nope

Thanks alot

**Comment by Hofknecht** [comment]
@petersnows25 
Thanks for the feedback!!

ah ok i understand now (i think).

I can reproduce it by e.g. move the STM to the second screen, then save the custom location by opening settings and pressing ok.
Then the STM restarts, now the custom location is on the second screen (see also https://github.com/Hofknecht/SystemTrayMenu/issues/278 how to save custom location).

Then I take over e.g. with the ipad only one screen (the primary screen, first screen). the STM receives a 'display changed' event and then restarts. If I now make a left click to open the menu, it appears outside of the area I see, so it does not appear.

As a workaround, I can now set the position to the bottom left in the settings. Then it appears with a left click. I can now drag it to the correct position and when I save again by going into settings and setting it back to 'custom location' and pressing ok. Then it always appears correct afterwards with 'custom location' over rdp.

Can you confirm that this workaround solves the issue?


we should change that when we receive a 'display changed' event that we check before restarting whether the custom location is still within the now new screens and if not then reset the custom location

(i will change title and flag it until solved as FAQ)
we added you in the thanks section in readme : )

**Comment by topeterk** [comment]
I would make this check upon actual presentation of the menu instead of updating the settings.
Image you use RDP once and then come back on the machine locally you would expect to see the menu on the second screen again, right?

**Comment by Hofknecht** [comment]
@petersnows25 thanks for creating the issue
@topeterk thanks for the hint

solved with version 1.2.0.6
