### ISSUE TITLE
[Feature] Remember Custom location between restarts

### ISSUE THREAD

**Issue by donaldaken** [Hofknecht/SystemTrayMenu#278]
I don't know if this is a feature request or a bug report. The Custom location for the menu does not survive a restart of SystemTrayMenu. 

Set "Main menu appears at" to "Custom (drag it to the appropriate place)". Drag the menu to a certain location. 
Close the menu. Hit Ctrl-Win or click the tray icon. The menu appears in the custom location.
Restart SystemTrayMenu by clicking the refresh icon, or clicking Restart on the tray icon, or restarting the computer. Hit Ctrl-Win or click the tray icon. The menu does **not** appear in the custom location. *[I think it appears at an earlier location, from before setting to Custom.]*

Expected behavior is to appear at the custom location - the location to which the menu was last dragged - regardless of restarting SystemTrayMenu.

BTW, I really like SystemTrayMenu. I searched the web in the past week and tried many apps. Tray Toolbar, Stacky, 7Stacks, and menuApp come close; but they don't look half as good. SystemTrayMenu lets me group apps. It's fast. It looks good. It's touchscreen-friendly, with settings to adjust size, tap once to launch, and hide menu after launching. It works equally well with a touchpad or keyboard. I love that it uses folders of shortcuts - I already know how to work with folders and shortcuts. KUDOS!!!

**Comment by Hofknecht** [comment]
@donaldaken 
Thank you very much for your feedback!
After the menu has been dragged to the right place, you have to open and save the settings, only then will the custom location be saved.

The reason for this is that we can only save all settings and not just one. So if we always save, then we also save the settings which were only temporarily changed in the settings menu. (This is only a issue when 'Show in Taskbar' disabled, otherwise you can not drag during settings menu open)

We could check whether the settings menu is open and if it is not open, then always save when it is moved. But then you could no longer move the menu temporarily and reset it at restart.

Now I think that the expectation is there that it will save directly, so we should change that

**Comment by donaldaken** [comment]
Thanks. Now I see, and it works. 

Maybe expand the note in Settings...
> Custom (drag it to the appropriate place, open Settings, and click OK)

**Comment by donaldaken** [comment]
Sorry. Accidentally closed. Still new to github.

**Comment by Hofknecht** [comment]
if we had to do it very quickly, it would definitely be helpful to adapt the text. But the 'full' solution is not a lot of effort, it will be there until the next version

feel free to try out all functions, you can't break them : )

**Comment by Hofknecht** [comment]
@donaldaken 
thanks for creating the issue

(we added you in the readme)

solved with version 1.2.0.4
