### ISSUE TITLE
[BUG] File name is cut off if it contains a point

### ISSUE THREAD

**Issue by akuznets** [Hofknecht/SystemTrayMenu#282]
**Description, Steps to reproduce, Expected behavior, Screenshots**
Link names get cut unexpectedly on dots, for instance:
"HWiNFO64.exe _7.14-4610; x64; HWiNFO64.lnk" is displayed as "HWiNFO64.exe _7" 
"localcooling2.exe _1.0.0.1; x32; LocalCooling 2.0.lnk"  is displayed "localcooling2.exe _1.0.0.1; x32; LocalCooling 2" 
"UserBenchMark.exe _2.9.5.0; x32; Benchmark Software.lnk"  is displayed  "UserBenchMark.exe _2.9.5" 
"cpuz_x64.exe _1.9.6.1; x64; CPU-Z Application.lnk"  is displayed  "cpuz_x64.exe _1.9.6" 
and so on for all 52 links that I have in the menu

if dots are replaced by commas the links are displayed fully

 - OS: [e.g. Microsoft Windows 10 Pro]:
 - Version [e.g. 0.9.1.233]
![image](https://user-images.githubusercontent.com/33734686/147776117-97c9b8bf-f847-4f24-bc9b-bb72abceafa0.png)
![image](https://user-images.githubusercontent.com/33734686/147776419-972991c3-8b91-44f7-be00-a69b03a25d0b.png)

**Comment by Hofknecht** [comment]
Hello @akuznets,
Thank you for the feedback!
especially the hint that it works if the point is replaced by a comma is very helpful!

i assume this is version 1.2.0.0

it sounds to be related to 
https://github.com/Hofknecht/SystemTrayMenu/issues/247

I just tried to reproduce that. i only have cpuz on my pc, but since it should be because of the name, it shouldn't make any difference. But it always works for me, see screenshots. So somehow I can't reproduce it right now.

![2021-12-30 23_09_49-+ (dot)   in shortcut, should open](https://user-images.githubusercontent.com/52528841/147791141-2d3764fd-198d-45d6-830c-a901302e8ae3.png)

![2021-12-30 23_04_17-+ (dot)   in shortcut, should open](https://user-images.githubusercontent.com/52528841/147791147-44fb0638-9b98-4abb-8a35-3abccf1ccbdf.png)

I'll try again tomorrow.

if anyone can reproduce this or sees what I am doing wrong while reproducing, I am grateful for every tip

**Comment by akuznets** [comment]
this is really strange coz same thing is happening to all of my 52 shortcuts, showing some of them with dots and with commas

![image](https://user-images.githubusercontent.com/33734686/147834850-3c962d3c-b7fc-42a7-89fc-85b8dc4adfe8.png)
![image](https://user-images.githubusercontent.com/33734686/147834856-b2e5f225-31c3-4326-b888-1bc4f5b9941c.png)

**Comment by Hofknecht** [comment]
@akuznets 
Thank you! Now we can reproduce!

First it was still working on my side even with your files:
![2022-01-01 10_40_47-](https://user-images.githubusercontent.com/52528841/147848003-9e6d7eea-2a7a-4a5b-a74a-1258df62a398.png)

Then we changed this option 'Hide extension for known file types' to true and then we can reproduce
![2022-01-01 10_44_40-Window](https://user-images.githubusercontent.com/52528841/147848020-968ab52a-c75e-4d6d-83c0-03203be31dc4.png)

![2022-01-01 10_44_21-](https://user-images.githubusercontent.com/52528841/147848024-ce9cb2d5-6734-4dde-800d-d766156d4714.png)



**=> Workaround is to set 'Hide extensions for known file types' to false**

We will add you into Thanks section in Readme.

**Comment by Hofknecht** [comment]
solved with version 1.2.0.8

here is our related test folder

![2022-01-01 12_30_27-Window](https://user-images.githubusercontent.com/52528841/147849680-475a8384-2749-4ffa-a202-abafada26e4d.png)

![2022-01-01 12_31_52-Window](https://user-images.githubusercontent.com/52528841/147849683-0da59af0-613c-42d8-b9c3-4b6d6d4408bb.png)

@akuznets
Thanks for find and help to solve it


=> closed
