### ISSUE TITLE
[BUG] "Store config at the assembly location"  not working for "protected folder locations"

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#321]
**Description, Steps to reproduce, Expected behavior, Screenshots**

Windows 11 Pro 22000.469, latest stable release. 
SystemTrayMenu 1.2.6.0 

I saw that you see reports from users and try to fix them.

I noticed that sometimes "Store config at the assembly location" does not place a user.config there and the tick does not stick in the settings box.
I think this is due to windows permissions blocking it when it is located in a protected location like "Program Files".

 I have UAC at minimum and run as administrator, Windows will not let me for example create a zip of a file or drop a browser bookmark shortcut into any folder in "Program Files".
The easiest way to test that strict permissions are in force on that folder is by right clicking a file and trying to make a shortcut of it. If you get this message you know access is restricted.

![Screenshot 2022-02-07 162248](https://user-images.githubusercontent.com/48499740/152828952-d3a6ceb4-f400-459b-8191-1cf6599395b8.png)

You should be able to reproduce this by moving the STM assembly location folder with an active user.config inside to a protected folder location, launch a new instance of STM from there and when you try to change settings in STM it will crash as it tries to edit the user.config and fails.

![Screenshot 2022-02-07 164232](https://user-images.githubusercontent.com/48499740/152833016-9b0ab05c-1304-4546-8ab6-775eb5a4bdd6.png)

Here if you try to create a new user.config it will not be created and the tickbox for "Store config at the assembly location" will remain unchecked.

**Comment by Hofknecht** [comment]
@chip33 
Thank you for reporting!
we will try to reproduce.

**Comment by Hofknecht** [comment]
exception now catched with version 1.2.6.2
instead you will find a log entry: Failed to store config at assembly location

but maybe it not solves your issue in that moment, you need to delete the file manually from the location since you also created it there, the application can not delete it. We use to place a user,config for import so we can also not ignore this and just save internal.

closed

@chip33
Is this ok? otherwise just reopen.
 if you want to you can retest and agree that is not more crashing at this pont.

**Comment by chip33** [comment]
Works well, no more crash and a warning in logfile !

thanks for fixing the blank line before the comment in my commit :)

**Comment by Hofknecht** [comment]
perfect, thank you for testing
