### ISSUE TITLE
[Feature] Option to store logfile at application directory instead into AppData

### ISSUE THREAD

**Issue by teamayu** [Hofknecht/SystemTrayMenu#371]
Currently running Windows 11. Really nice software, but why does it write the logs and config file to:
AppData/Roaming/SystemTrayMenu/*

?

**Comment by Hofknecht** [comment]
@teamayu 
thanks for the question

might be related to
https://github.com/Hofknecht/SystemTrayMenu/issues/120

maybe also this link
https://stackoverflow.com/questions/982354/where-are-the-properties-settings-default-stored#:~:text=If%20you%20store%20settings%20for,public%5Cappdata%5Clocal%20

i think it was when we put it in the app store there was the issue that logfile could not be written at same location as the exe

config file can be written into assembly location at portable version to import and export config
![2022-04-01 21_02_06-Window](https://user-images.githubusercontent.com/52528841/161325752-15c57ce2-b34b-4f1c-9647-f0fd8486bd52.png)

At which place would you have expected the log and the config?

**Comment by Hofknecht** [comment]
You can also open the log here, right click on the system tray icon

![2022-04-01 21_05_30-](https://user-images.githubusercontent.com/52528841/161326134-b713a5bd-98eb-4aae-9cae-a11f9357bec3.png)

**Comment by teamayu** [comment]
Thanks for the info. Yes, it would be ideal if the data could be written to the same folder that the software is run from. Not a deal breaker though.

**Comment by Hofknecht** [comment]
i think we will implement to store logfile at assembly location and we will try to set this and store config at assembly location as default in the portable version

**Comment by Hofknecht** [comment]
Implemented in version 1.2.9.11

Some notes:
is also default false for portable version because it is possible that you only have read rights also in the portable app.

If you switch the setting on and have no rights when applying the setting, exiting the app or when starting the app, it is automatically switched off again and logged into logfile that there are no rights

also fixed that current logfile is shown on top if there are 2 logfiles

also fixed if the log file gets too big, a backup is made and a new log file is started, if that goes wrong, it was not logged

moved a bit the layout e.g.  'Use icon from directory' moved from General to Customize tab
