### ISSUE TITLE
[Feature] Option which function keys are shown

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#401]
I have never been sure what effect toggling the Pin icon in the function keys actually has.
For a cleaner interface Is it possible to add an option to not show the Pin icon as a subset of Settings > Customize > Show function keys below > 

![Screenshot 2022-06-19 114044](https://user-images.githubusercontent.com/48499740/174477580-9c75b573-6ae2-4e73-9111-ec73a92d5d13.png)

Also do we still need the Refresh Root Folder icon now that [330](https://github.com/Hofknecht/SystemTrayMenu/issues/330#event-6828725793) is complete?
Is it safe to remove this icon altogether now or is it possible to add an option to also not show the Refresh Root Folder icon as a subset of Settings > Customize > Show function keys below >

**Comment by Hofknecht** [comment]
@chip33 
Thanks for the feedback!

The pin symbol is used for debugging and theoretically to drag url into a submenu. Theoretically also e.g. to place a menu in one place, which i don't think is used very often.
It's a good idea that you can possibly switch on the functions individually there.
The refresh can be removed, that's true, it's no longer needed since #330

Here we will do something!
