### ISSUE TITLE
[BUG] Scrollbar visible in Options menu

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#409]
With my 4K@350% display scaling monitor and the new release 1.3..0.0 the Options menu always opens with the vertical scroll bar showing. This was working correctly in 1.2.9.31

![Screenshot 2022-07-11 130651](https://user-images.githubusercontent.com/48499740/178260607-2a48fccd-daa1-4a85-a792-010ad1b2afa4.png)

Also, a small thing but the "Abort" label for the button to close the Options menu feels misnamed (as no changes would be made if the user just clicks close button on top right).
It is slightly confusing and less "friendly" compared to the more familiar "Cancel" button

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the hint, we will have a look

**Comment by Hofknecht** [comment]
@chip33 
i test on a normal screen with 175%, there it was working, could not reproduce, i need a 4k screen ; ) 
i adjusted something, can you test if it works now?

we will also change the Abort -> Cancel (we changed to abort because of automatic translations, but you are right, abort sounds strange here)

**Comment by chip33** [comment]
@Hofknecht . Yes, tested 1.3.0.1 and it is now working correctly, the scrollbar is now gone.

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the feedback!
Now also Abort renamed to Cancel
