### ISSUE TITLE
[Feature] Adjust width when items deleted

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#431]
If items are removed from the root menu the menu height now refreshes automatically to reflect the change but the menu width stays wider until it is restarted manually.

![Screenshot 2022-08-03 074515](https://user-images.githubusercontent.com/48499740/182545478-274f9cc8-1898-4828-85e1-b0548e68242a.png)

![Screenshot 2022-08-03 080429](https://user-images.githubusercontent.com/48499740/182545510-81047360-2f02-420e-b128-f8fcd9c877cd.png)

**Comment by chip33** [comment]
PS, sorry for posting so much, I just really this app and enjoy testing it :)

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the feedback!
we will have a look

**Comment by Hofknecht** [comment]
@chip33 
we looked at it. So it worked for us The width is adjusted when creating and deleting.

We have a guess as to what it could be.
was the menu so wide before the file was created or was it really so wide when it was created?
Did you show additional folders for search? If yes, then type into search * (asterisk) to see all items. Then scroll through all the items to see if there is a second item that is very long.
We shouldn't adjust the width when searching, so for all items that can be found by searching, the maximum width of the items will be calculated.

Otherwise we need a hint on how you did it : )

**Comment by chip33** [comment]
@Hofknecht 
Ah yes, this only occurs when the Search bar is hidden!
When the Search bar is shown the width does resize automatically.
![Screenshot 2022-08-06 164358](https://user-images.githubusercontent.com/48499740/183256637-2bcbfe1e-fca0-4296-9fa6-cad13b039363.png)

If you hide the Search bar then deleting a long file "check_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt" from the root directory results in the following behaviour until STM is restarted manually.
![Screenshot 2022-08-06 165436_](https://user-images.githubusercontent.com/48499740/183256813-039c2413-5f23-475e-8d2f-c11c70204b1e.png)

![Screenshot 2022-08-06 165528](https://user-images.githubusercontent.com/48499740/183256839-d1b7a948-8c05-4b48-8024-60de3b6cb8c2.png)

**Comment by Hofknecht** [comment]
@chip33 
Thanks for pointing that out, now we've been able to reproduce it and it's fixed!
