### ISSUE TITLE
[BUG] Duplicate file/folder name causes unexpected result on opening

### ISSUE THREAD

**Issue by boydfields** [Hofknecht/SystemTrayMenu#434]
**Situation:**  A folder and a file or shortcut named the same.

![explorer_Kov5r5xHoF](https://user-images.githubusercontent.com/46451679/182829233-88794157-720b-4c2d-a296-7a942ef3c152.png)

**Outcome:**  Double clicking on the folder within SystemTrayMenu executes the file or shortcut.

**Expected result:**  SystemTrayMenu should open Explorer to browse the folder contents.

![RoyalTS_USqeHlJoZx](https://user-images.githubusercontent.com/46451679/182828679-2e507c07-b612-474f-a061-6b62794f662b.png)

 - OS: Windows 10 Enterprise:
 - OS Version: 19044.1766
 - App version: 1.3.0.0

Please let me know if you require further information.
Many thanks

**Comment by Hofknecht** [comment]
@boydfields
Thank you for the feedback!
We will have a look.

**Comment by Hofknecht** [comment]
@boydfields 
the problem was that if there is a shortcut with the same name as a folder in the same place, you need a backslash at the end of the path, otherwise the shortcut will be called at processStart. This is strange, since a link actually has an extension "*.lnk".
ok lesson learned, is fixed now with version 1.3.0.15

**Comment by boydfields** [comment]
Much appreciated :)
