### ISSUE TITLE
[BUG] - When any open window minimizes toolbar triggers and opens up

### ISSUE THREAD

**Issue by millowster** [Hofknecht/SystemTrayMenu#447]
**Description, Steps to reproduce, Expected behavior, Screenshots**

1. Make sure toolbar is on or open in the taskbar by using it once by clicking it.
2. Then any open windows you have or do open just minimize them 
3. Once you Minimize it the SystemTrayMenu will trigger open as if you clicked on it.

 - OS: [e.g. Microsoft Windows 10 Pro]:
 - Version [e.g. 0.9.1.233]

**Comment by Hofknecht** [comment]
Hello @millowster 
Thank you for the feedback! sorry for late reply.

Yes that's correct.
feature is: #115
we added a option and then removed here: #123 #137
and added again here: #230

a simple taskbar item had certain advantages, but also had the disadvantage. When a program is disabled, the previous one is enabled by windows by default. That means if we have a taskbarform then we will be activated automatically. This can only be prevented by removing the taskbar item.

Find the option therefore here:
![2022-09-19 20_20_36- BUG  - When any open window minimizes toolbar triggers and opens up · Issue #44](https://user-images.githubusercontent.com/52528841/191086938-a62ff72a-4b95-45dd-99bb-b5412c76405d.png)

there then we decided that this option should be on by default to ensure easier access to the tool. It can also have advantages, e.g. I often use this behavior that when exit a game STM opens automatically and i can choose next (currently i am implementing gamepad support so that I no longer have to get up from the couch with a gamepad on the pc to change the game, which is exactly what this behavior requires, since I can only read the signals from the gamepad when the STM is active/open)

i will mark this as FAQ and close

if it is unclear or if you have other questions, you are welcome to open the task again.

please also let us know if the behavior suits you if you deactivate the option
