### ISSUE TITLE
Option "Autostart (Task Manager)

### ISSUE THREAD

**Issue by FranksPizzaTM** [Hofknecht/SystemTrayMenu#476]
When I click on "Start with Windows" SystemTrayMenu does not appear when signing into my Desktop.  SystemTrayMenu does not Start with Windows.  Please help?  Thank you, Tim

**Comment by Hofknecht** [comment]
Hey @FranksPizzaTM / Tim
Thank you for the feedback!

 Jul 8, 2019  - Fixed autostart for portable version
https://github.com/Hofknecht/SystemTrayMenu/issues/28

Oct 23, 2021 - Implemented autostart for UWP / Microsoft Store
https://github.com/Hofknecht/SystemTrayMenu/issues/131

In principle it should work, there have been no more complaints for a few years that it doesn't work.
The first question would be whether you are using the microsoft store version or the portable version?

In the portable version it looks like this:
![2023-03-27 14_51_01-Window](https://user-images.githubusercontent.com/52528841/227945001-699e3d83-fdfe-4a20-bb29-7ef2b45d6d22.png)
When enable the checkbox and pressing 'OK' we try to add a registry entry for autostart. i never saw this failing, but when it fails there would be something in the logfile. You can open the logfile via systemtray icon right click -> 'Log File'

In the Microsoft Store version / UWP it was a bit more efford to implement, because there are no rights to touch registry, there seems to be only one correct way, which we implemented in #131
![2023-03-27 15_00_02-Window](https://user-images.githubusercontent.com/52528841/227946339-c9e1043a-7243-4ea1-8e44-7d1b92d2affd.png)
(You mentioned click, so i assume you are using Microsoft Store / UWP)
Here also a autostart entry will be created with status 'enabled'.  You can find the entries in Task Manager.
From experience we saw back then that if the user sets it from enabled to disabled, the UWP app cannot change the entry (lack of rights). If the user disables it via the task manager, he must reactivate it himself via the task manager.
![2023-03-27 14_59_14-Window](https://user-images.githubusercontent.com/52528841/227946214-00f469cd-9249-43e1-bb85-e907043ba146.png)

So our question are:
-Do you use UWP app?
-Do you find the entry in Task Manager?
-Is the status disabled and did you set it disabled manually by yourself?
-Does it work when you reactivate it via task manager?

**Comment by Hofknecht** [comment]
BTW it looks like this when deactivated and pressing the button
![2023-03-27 15_08_38-Window](https://user-images.githubusercontent.com/52528841/227947469-1ca8cf83-96d9-4a70-8234-c96956caf10e.png)
Maybe instead of 'Deactivated' we could show a better explanation ; )

In your case does it says 'Deactivated'? Or any other text? when there is nothing please send also the logfile

**Comment by FranksPizzaTM** [comment]
Thank you for your assistance!  I used your workaround #131:  https://winaero.com/add-store-apps-startup-windows-10/  The SystemTrayMenu application now starts when I sign onto both my Administrator and Standard User accounts!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by FranksPizzaTM** [comment]
Continued…although SystemTrayMenu works with the shortcut in place your app still shows “disabled” in Task Manager.  Again regardless of the “disabled” status SystemTrayManager still starts upon signing into boty standard user and administrator accounts in Windows 11.  Thanks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
