### ISSUE TITLE
[Feature]  Show hint to find settings and enable by default 'Show function key Settings'

### ISSUE THREAD

**Issue by TrampiPW** [Hofknecht/SystemTrayMenu#490]
Hi Markus,

thanks for this great tool. By mistake I disabled the system tray icon and now the configuration screen is not reachable. Is there any way to reset the configuration?

best regards

Markus

**Comment by TrampiPW** [comment]
Hi Markus, 
still great tool but not robust against incompetent user 😢. I found the icon in the system tray. Sorry.
best regards
Markus

**Comment by Hofknecht** [comment]
@TrampiPW 
Sorry for late response.
Thank you for the feedback and let us know about that you found the option settings via the systemtray icon right click!
We've heard this before, so you're not the only one. Especially since #401 when we not show option by default in menu, then there were users reporting that they can not find the option menu any longer. I'm just thinking if we should show all 4 extra function by default?

**Comment by Hofknecht** [comment]
Because i have also these 4 functions enabled, normally the default settings are as i use them:
![2023-07-29 10_43_35-Window](https://github.com/Hofknecht/SystemTrayMenu/assets/52528841/72d400a7-d6ae-4e28-8307-5e9ab657fe07)
So consider to enable all by default, because i think also for first user is good that it exists there.
Maybe now i think first time user opens the options menu we can show a hint that you can also open the options menu via systemtray icon right click

**Comment by Hofknecht** [comment]
e.g. here is one more

![2023-07-30 09_28_51-Window](https://github.com/Hofknecht/SystemTrayMenu/assets/52528841/446fae55-e85e-4259-b508-a4e28f4bfc95)

---

i just think maybe when you user removes the option 'Show in Taskbar' then we show him a hint, that the can find options via systemtray icon right click, maybe also with a screenshot in a dialog where he presses then 'OK'

![2023-07-30 09_30_19-Window](https://github.com/Hofknecht/SystemTrayMenu/assets/52528841/6f7ae4ec-390d-4dee-811a-936a34cf5a6f)

**Comment by Hofknecht** [comment]
@TrampiPW 
1
Now function keys visible in menu by default

2
Now there is a hint when disable
Show in Taskbar OR
Show function key 'Settings'
![2023-07-30 14_50_05-Window](https://github.com/Hofknecht/SystemTrayMenu/assets/52528841/106a22c4-e403-4350-92d0-35b9a02abb73)
we added you to the thanks section
