### ISSUE TITLE
[Feature] Improve shortcut key to start STM

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#56]
maybe 'numpad 0'

**Comment by Hofknecht** [comment]
at the moment we allow combinations of 
Ctrl+Alt+<select a key> 

are there better possiblities?
we made this because windows allows also only Ctrl+Alt+<select a key>  for shortcuts on desktop but not sure why we made this limitation.

Another problem is, we would overwrite the user the  'numpad 0'

Other non stm solutions:
1. use keyboard with macros an map to  'Ctrl+Alt+<select a key>' (i use it like this, therefore prefered combination is 'Ctrl+Alt+F10', because most combinations are taken by other programms and this one seems to be ok, also working with e.g. rdp)
2. use autohotkey to map 'numpad 0' to 'Ctrl+Alt+<select a key>'

**Comment by Hofknecht** [comment]
e.g. greenshot has good behavior, for some key's only allowed with control shift for other like 'print' it is possible to assign directly

![image](https://user-images.githubusercontent.com/52528841/78513667-9a4ce680-77ad-11ea-8919-7fcf1d579760.png)

**Comment by Hofknecht** [comment]
was done with #55
https://github.com/Hofknecht/SystemTrayMenu/issues/55
